apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.changecourse: RollingBack
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-08-01T06:48:47Z
  generation: 1
  labels:
    qcloud-app: aa
  name: aa
  namespace: u42560779
  resourceVersion: "32447265795"
  selfLink: /apis/extensions/v1beta1/namespaces/u42560779/deployments/aa
  uid: f0c9c0b1-9556-11e8-99b3-52540015776a
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      qcloud-app: aa
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        qcloud-app: aa
    spec:
      containers:
      - env:
        - name: PATH
          value: /go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: GOLANG_VERSION
          value: 1.10.3
        - name: GOPATH
          value: /go
        image: hub.tencentyun.com/bbhj/wechat:latest
        imagePullPolicy: Always
        name: wechat
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      restartPolicy: Always
      securityContext: {}
      serviceAccountName: ""
      terminationGracePeriodSeconds: 30
      volumes: null
status:
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/qcloud-loadbalancer-clusterid: cls-a4ed48t8
  creationTimestamp: 2018-08-01T06:48:47Z
  labels:
    qcloud-app: test
  name: test
  namespace: u42560779
  resourceVersion: "32447297642"
  selfLink: /api/v1/namespaces/u42560779/services/test
  uid: f0d116a5-9556-11e8-99b3-52540015776a
spec:
  clusterIP: 172.16.255.116
  ports:
  - name: tcp-9090-9090-niltt
    nodePort: 30901
    port: 8080
    protocol: TCP
    targetPort: 9090
  selector:
    qcloud-app: test
  sessionAffinity: None
